let fakeData = [
  {
    id: 1,
    name: 'Chiles en Nogada (Mexican Stuffed Poblano Peppers in Walnut Sauce)',
    ingredients: [
      {
        quantity: 8,
        quantity2: null,
        unitOfMeasure: null,
        description: 'poblano peppers',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: 'tablespoon',
        description: 'olive oil',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'onion, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: null,
        description: 'cloves garlic, finely chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1.75,
        quantity2: null,
        unitOfMeasure: 'pounds',
        description: 'ground pork',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'peeled, seeded, and chopped tomatoes',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'ripe plantain, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'apple, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'fresh peach, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'bunch fresh parsley, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'chopped candied orange peel',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'pine nuts',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'raisins',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'blanched almonds, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 4,
        quantity2: null,
        unitOfMeasure: null,
        description: 'whole cloves, ground',
        isGroupHeader: false,
      },
      {
        quantity: null,
        quantity2: null,
        unitOfMeasure: null,
        description: 'salt and pepper to taste',
        isGroupHeader: false,
      },
      {
        quantity: 2.5,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'chopped walnuts',
        isGroupHeader: false,
      },
      {
        quantity: 1.75,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'milk',
        isGroupHeader: false,
      },
      {
        quantity: 0.75,
        quantity2: null,
        unitOfMeasure: 'cup',
        description: 'soft goat cheese',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: 'tablespoon',
        description: 'white sugar',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: '(1 inch) piece cinnamon stick',
        isGroupHeader: false,
      },
      {
        quantity: 1.5,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'pomegranate seeds',
        isGroupHeader: false,
      },
      {
        quantity: 0.5,
        quantity2: null,
        unitOfMeasure: 'cup',
        description: 'chopped fresh parsley',
        isGroupHeader: false,
      },
    ],
    instructions: [
      'Roast poblano chiles over an open flame on a gas stove or grill until the skin is black and charred on all sides, turning often, 10 to 15 minutes.',
      'Place the charred chiles in a plastic bag or in a large bowl covered with plastic wrap. Allow to sit for 5 to 10 minutes, then open and peel off the skin. Cut a slit in each chile lengthwise and remove the seeds.',
      'Heat olive oil in a large pot over medium heat. Add onion and garlic and cook until soft and translucent, 3 to 4 minutes. Add ground pork and cook until browned, breaking up with a spoon while cooking, about 7 minutes. Mix in tomatoes, plantain, apple, peach, parsley, candied orange peel, pine nuts, raisins, almonds, cloves, salt, and pepper. Simmer until filling is cooked through and flavors are well combined, about 10 minutes.',
      'Combine walnuts, milk, goat cheese, sugar, and cinnamon stick in a blender; blend until walnut sauce is smooth and creamy.',
      'Fill each poblano chile with the pork filling and place on a plate. Spoon walnut sauce over chile and sprinkle with pomegranate seeds and parsley.',
    ],
    tags: [],
    time: {
      prep: '1 hr',
      cook: '30 mins',
      active: '',
      inactive: '5 mins',
      ready: '',
      total: '1 hr 35 mins',
    },
    urlSource:
      'https://www.allrecipes.com/recipe/259373/chiles-en-nogada-mexican-stuffed-poblano-peppers-in-walnut-sauce/',
    servings: 8,
    image:
      'https://imagesvc.meredithcorp.io/v3/mm/image?q=85&c=sc&poi=face&w=1750&h=875&url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4543290.jpg',
  },
  {
    id: 2,
    name: 'Chiles en Nogada (Mexican Stuffed Poblano Peppers in Walnut Sauce)',
    ingredients: [
      {
        quantity: 8,
        quantity2: null,
        unitOfMeasure: null,
        description: 'poblano peppers',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: 'tablespoon',
        description: 'olive oil',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'onion, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: null,
        description: 'cloves garlic, finely chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1.75,
        quantity2: null,
        unitOfMeasure: 'pounds',
        description: 'ground pork',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'peeled, seeded, and chopped tomatoes',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'ripe plantain, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'apple, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'fresh peach, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'bunch fresh parsley, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'chopped candied orange peel',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'pine nuts',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'raisins',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'blanched almonds, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 4,
        quantity2: null,
        unitOfMeasure: null,
        description: 'whole cloves, ground',
        isGroupHeader: false,
      },
      {
        quantity: null,
        quantity2: null,
        unitOfMeasure: null,
        description: 'salt and pepper to taste',
        isGroupHeader: false,
      },
      {
        quantity: 2.5,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'chopped walnuts',
        isGroupHeader: false,
      },
      {
        quantity: 1.75,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'milk',
        isGroupHeader: false,
      },
      {
        quantity: 0.75,
        quantity2: null,
        unitOfMeasure: 'cup',
        description: 'soft goat cheese',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: 'tablespoon',
        description: 'white sugar',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: '(1 inch) piece cinnamon stick',
        isGroupHeader: false,
      },
      {
        quantity: 1.5,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'pomegranate seeds',
        isGroupHeader: false,
      },
      {
        quantity: 0.5,
        quantity2: null,
        unitOfMeasure: 'cup',
        description: 'chopped fresh parsley',
        isGroupHeader: false,
      },
    ],
    instructions: [
      'Roast poblano chiles over an open flame on a gas stove or grill until the skin is black and charred on all sides, turning often, 10 to 15 minutes.',
      'Place the charred chiles in a plastic bag or in a large bowl covered with plastic wrap. Allow to sit for 5 to 10 minutes, then open and peel off the skin. Cut a slit in each chile lengthwise and remove the seeds.',
      'Heat olive oil in a large pot over medium heat. Add onion and garlic and cook until soft and translucent, 3 to 4 minutes. Add ground pork and cook until browned, breaking up with a spoon while cooking, about 7 minutes. Mix in tomatoes, plantain, apple, peach, parsley, candied orange peel, pine nuts, raisins, almonds, cloves, salt, and pepper. Simmer until filling is cooked through and flavors are well combined, about 10 minutes.',
      'Combine walnuts, milk, goat cheese, sugar, and cinnamon stick in a blender; blend until walnut sauce is smooth and creamy.',
      'Fill each poblano chile with the pork filling and place on a plate. Spoon walnut sauce over chile and sprinkle with pomegranate seeds and parsley.',
    ],
    tags: [],
    time: {
      prep: '1 hr',
      cook: '30 mins',
      active: '',
      inactive: '5 mins',
      ready: '',
      total: '1 hr 35 mins',
    },
    urlSource:
      'https://www.allrecipes.com/recipe/259373/chiles-en-nogada-mexican-stuffed-poblano-peppers-in-walnut-sauce/',
    servings: 8,
    image:
      'https://imagesvc.meredithcorp.io/v3/mm/image?q=85&c=sc&poi=face&w=1750&h=875&url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4543290.jpg',
  },
  {
    id: 3,
    name: 'Chiles en Nogada (Mexican Stuffed Poblano Peppers in Walnut Sauce)',
    ingredients: [
      {
        quantity: 8,
        quantity2: null,
        unitOfMeasure: null,
        description: 'poblano peppers',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: 'tablespoon',
        description: 'olive oil',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'onion, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: null,
        description: 'cloves garlic, finely chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1.75,
        quantity2: null,
        unitOfMeasure: 'pounds',
        description: 'ground pork',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'peeled, seeded, and chopped tomatoes',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'ripe plantain, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'apple, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'fresh peach, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'bunch fresh parsley, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'chopped candied orange peel',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'pine nuts',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'raisins',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'blanched almonds, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 4,
        quantity2: null,
        unitOfMeasure: null,
        description: 'whole cloves, ground',
        isGroupHeader: false,
      },
      {
        quantity: null,
        quantity2: null,
        unitOfMeasure: null,
        description: 'salt and pepper to taste',
        isGroupHeader: false,
      },
      {
        quantity: 2.5,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'chopped walnuts',
        isGroupHeader: false,
      },
      {
        quantity: 1.75,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'milk',
        isGroupHeader: false,
      },
      {
        quantity: 0.75,
        quantity2: null,
        unitOfMeasure: 'cup',
        description: 'soft goat cheese',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: 'tablespoon',
        description: 'white sugar',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: '(1 inch) piece cinnamon stick',
        isGroupHeader: false,
      },
      {
        quantity: 1.5,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'pomegranate seeds',
        isGroupHeader: false,
      },
      {
        quantity: 0.5,
        quantity2: null,
        unitOfMeasure: 'cup',
        description: 'chopped fresh parsley',
        isGroupHeader: false,
      },
    ],
    instructions: [
      'Roast poblano chiles over an open flame on a gas stove or grill until the skin is black and charred on all sides, turning often, 10 to 15 minutes.',
      'Place the charred chiles in a plastic bag or in a large bowl covered with plastic wrap. Allow to sit for 5 to 10 minutes, then open and peel off the skin. Cut a slit in each chile lengthwise and remove the seeds.',
      'Heat olive oil in a large pot over medium heat. Add onion and garlic and cook until soft and translucent, 3 to 4 minutes. Add ground pork and cook until browned, breaking up with a spoon while cooking, about 7 minutes. Mix in tomatoes, plantain, apple, peach, parsley, candied orange peel, pine nuts, raisins, almonds, cloves, salt, and pepper. Simmer until filling is cooked through and flavors are well combined, about 10 minutes.',
      'Combine walnuts, milk, goat cheese, sugar, and cinnamon stick in a blender; blend until walnut sauce is smooth and creamy.',
      'Fill each poblano chile with the pork filling and place on a plate. Spoon walnut sauce over chile and sprinkle with pomegranate seeds and parsley.',
    ],
    tags: [],
    time: {
      prep: '1 hr',
      cook: '30 mins',
      active: '',
      inactive: '5 mins',
      ready: '',
      total: '1 hr 35 mins',
    },
    urlSource:
      'https://www.allrecipes.com/recipe/259373/chiles-en-nogada-mexican-stuffed-poblano-peppers-in-walnut-sauce/',
    servings: 8,
    image:
      'https://imagesvc.meredithcorp.io/v3/mm/image?q=85&c=sc&poi=face&w=1750&h=875&url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4543290.jpg',
  },
  {
    id: 4,
    name: 'Chiles',
    ingredients: [
      {
        quantity: 8,
        quantity2: null,
        unitOfMeasure: null,
        description: 'poblano peppers',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: 'tablespoon',
        description: 'olive oil',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'onion, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: null,
        description: 'cloves garlic, finely chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1.75,
        quantity2: null,
        unitOfMeasure: 'pounds',
        description: 'ground pork',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'peeled, seeded, and chopped tomatoes',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'ripe plantain, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'apple, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'fresh peach, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'bunch fresh parsley, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'chopped candied orange peel',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'pine nuts',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'raisins',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'blanched almonds, chopped',
        isGroupHeader: false,
      },
      {
        quantity: 4,
        quantity2: null,
        unitOfMeasure: null,
        description: 'whole cloves, ground',
        isGroupHeader: false,
      },
      {
        quantity: null,
        quantity2: null,
        unitOfMeasure: null,
        description: 'salt and pepper to taste',
        isGroupHeader: false,
      },
      {
        quantity: 2.5,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'chopped walnuts',
        isGroupHeader: false,
      },
      {
        quantity: 1.75,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'milk',
        isGroupHeader: false,
      },
      {
        quantity: 0.75,
        quantity2: null,
        unitOfMeasure: 'cup',
        description: 'soft goat cheese',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: 'tablespoon',
        description: 'white sugar',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: '(1 inch) piece cinnamon stick',
        isGroupHeader: false,
      },
      {
        quantity: 1.5,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'pomegranate seeds',
        isGroupHeader: false,
      },
      {
        quantity: 0.5,
        quantity2: null,
        unitOfMeasure: 'cup',
        description: 'chopped fresh parsley',
        isGroupHeader: false,
      },
    ],
    instructions: [
      'Roast poblano chiles over an open flame on a gas stove or grill until the skin is black and charred on all sides, turning often, 10 to 15 minutes.',
      'Place the charred chiles in a plastic bag or in a large bowl covered with plastic wrap. Allow to sit for 5 to 10 minutes, then open and peel off the skin. Cut a slit in each chile lengthwise and remove the seeds.',
      'Heat olive oil in a large pot over medium heat. Add onion and garlic and cook until soft and translucent, 3 to 4 minutes. Add ground pork and cook until browned, breaking up with a spoon while cooking, about 7 minutes. Mix in tomatoes, plantain, apple, peach, parsley, candied orange peel, pine nuts, raisins, almonds, cloves, salt, and pepper. Simmer until filling is cooked through and flavors are well combined, about 10 minutes.',
      'Combine walnuts, milk, goat cheese, sugar, and cinnamon stick in a blender; blend until walnut sauce is smooth and creamy.',
      'Fill each poblano chile with the pork filling and place on a plate. Spoon walnut sauce over chile and sprinkle with pomegranate seeds and parsley.',
    ],
    tags: [],
    time: {
      prep: '1 hr',
      cook: '30 mins',
      active: '',
      inactive: '5 mins',
      ready: '',
      total: '1 hr 35 mins',
    },
    urlSource:
      'https://www.allrecipes.com/recipe/259373/chiles-en-nogada-mexican-stuffed-poblano-peppers-in-walnut-sauce/',
    servings: 8,
    image:
      'https://imagesvc.meredithcorp.io/v3/mm/image?q=85&c=sc&poi=face&w=1750&h=875&url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4543290.jpg',
  },
  {
    id: 5,
    name: 'Authentic Mole Sauce',
    ingredients: [
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'cups',
        description: 'chicken broth',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: null,
        description: 'dried guajillo chiles, stemmed and seeded',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: null,
        description: 'dried ancho chiles, stemmed and seeded',
        isGroupHeader: false,
      },
      {
        quantity: 3,
        quantity2: null,
        unitOfMeasure: null,
        description: 'dried chipotle chiles, stemmed and seeded',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'dinner roll, torn into pieces',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: null,
        description: 'corn tortillas, cut into 1-inch strips',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: null,
        description: 'tomatoes, cut in half crosswise',
        isGroupHeader: false,
      },
      {
        quantity: 5,
        quantity2: null,
        unitOfMeasure: null,
        description: 'tomatillos, cut in half crosswise',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: 'tablespoon',
        description: 'lard',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: null,
        description: 'onion, halved and thinly sliced',
        isGroupHeader: false,
      },
      {
        quantity: 0.5,
        quantity2: null,
        unitOfMeasure: null,
        description: 'head garlic, peeled and sliced',
        isGroupHeader: false,
      },
      {
        quantity: 0.333,
        quantity2: null,
        unitOfMeasure: 'cup',
        description: 'chopped peanuts',
        isGroupHeader: false,
      },
      {
        quantity: 0.25,
        quantity2: null,
        unitOfMeasure: 'cup',
        description: 'raisins',
        isGroupHeader: false,
      },
      {
        quantity: 2,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'cumin seeds',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: 'tablespoon',
        description: 'dried thyme',
        isGroupHeader: false,
      },
      {
        quantity: 3,
        quantity2: null,
        unitOfMeasure: null,
        description: 'cinnamon sticks',
        isGroupHeader: false,
      },
      {
        quantity: 5,
        quantity2: null,
        unitOfMeasure: null,
        description: 'whole cloves',
        isGroupHeader: false,
      },
      {
        quantity: 6,
        quantity2: null,
        unitOfMeasure: null,
        description: 'whole allspice berries',
        isGroupHeader: false,
      },
      {
        quantity: 5,
        quantity2: null,
        unitOfMeasure: 'ounces',
        description: 'dark chocolate, coarsely chopped',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: 'cup',
        description: 'chicken broth',
        isGroupHeader: false,
      },
      {
        quantity: 3,
        quantity2: null,
        unitOfMeasure: 'tablespoons',
        description: 'white sugar',
        isGroupHeader: false,
      },
      {
        quantity: 1,
        quantity2: null,
        unitOfMeasure: 'teaspoon',
        description: 'salt',
        isGroupHeader: false,
      },
    ],
    instructions: [
      'Toast guajillo chiles, ancho chiles, and chipotle chiles in a dry pan over medium heat, stirring constantly, until warm and aromatic, about 3 minutes. Transfer to the blender with chicken broth.',
      'Heat 2 cups chicken broth in a saucepan until it begins to simmer, about 5 minutes. Pour broth into a blender.',
      'Toast dinner roll pieces and tortilla strips in a dry pan over medium heat, stirring constantly, until lightly browned, about 3 minutes. Transfer to the blender with chicken broth and chiles',
      'Allow the chiles and toasted bread and tortillas to soak, fully submerged, in the chicken broth until softened, about 10 minutes. Blend the mixture until smooth.',
      'Cook tomatoes and tomatillos in a dry skillet on medium-high heat until soft and blackened, 3 to 4 minutes per side. Place tomatoes in the blender with the chile puree.',
      'Melt lard in a large skillet over medium heat. Stir in onion, garlic, peanuts, raisins, cumin seeds, thyme, cinnamon sticks, cloves, and allspice berries; cook and stir until onions are soft and golden, 5 to 8 minutes. Remove the cinnamon sticks and other whole spices; add onion mixture to the blender with the chile-tomato mixture and blend until smooth.',
      'Pour chile puree into a large saucepan over medium heat. Stir in chocolate chicken broth, sugar, and salt. Bring mixture to a simmer; stir until chocolate is melted and sauce is thickened and slightly reduced, 10 to 15 minutes.',
    ],
    tags: [],
    time: {
      prep: '20 mins',
      cook: '30 mins',
      active: '',
      inactive: '10 mins',
      ready: '',
      total: '1 hr',
    },
    servings: '4\n',
    image:
      'https://imagesvc.meredithcorp.io/v3/mm/image?q=85&c=sc&poi=face&w=1536&h=768&url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1037459.jpg',
    urlSource: 'https://www.allrecipes.com/recipe/223261/authentic-mole-sauce/',
  },
];

export default fakeData;
